spring:
  datasource:
    name: student_Info  #数据库名
    url: jdbc:mysql://localhost:3306/student_info?characterEncoding=UTF-8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:dao/*.xml  #配置映射文件
  type-aliases-package: com.example.studentmanagementsystem.bean #配置实体类